---
name: Lint Code Base

on: push

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v5

  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            GITHUB_REF="${{ github.ref }}"
            GITHUB_REPOSITORY="${{ github.repository }}"
            GITHUB_SHA="${{ github.sha }}"
